### ISSUE TITLE
Idea: use MacroTools.jl?

### ISSUE THREAD

**Issue by alhirzel** [aminya/AcuteML.jl#149]
I know at this point it could be a heroic effort, but after looking at the parser for `@aml`, I thought it would be appropriate to suggest usage of [MacroTools.jl](https://fluxml.ai/MacroTools.jl/stable/pattern-matching/) and their `@capture` macro. It might be the biggest help around here: https://github.com/aminya/AcuteML.jl/blob/6b87580529082ad3734a896151f3d5821f8d82b3/src/%40aml/%40aml_parse.jl#L51-L389

**Comment by aminya** [comment]
The code is `@aml_parse` works without any issues. I have written the parsing code manually by hand which in addition to being correct, is much more performant than using a `@capture` macro which is limited in functionality. 

Once, I tried to add something to MacroTools, but it never got through. I am not interested in adding a dependency for a project that is impossible to update.
https://github.com/FluxML/MacroTools.jl/pull/136

**Comment by alhirzel** [comment]
Aha, I should have done a better search! Thank you for the background and reasoning.

**Comment by aminya** [comment]
You're welcome. A simplified version of this parsing code exist at https://github.com/aminya/VarStructs.jl/blob/master/src/parse.jl

I might be able to refactor `varTdefVal` and `varT` in the future if I found time.

**Comment by alhirzel** [comment]
That's an interesting package that I had not yet seen, thank you for the pointer!
